**importing libraries**

In [3]:
import numpy as np
from numpy import array 
from numpy import random 
from numpy import dot 
from random import choice

***Intialized dataset***

In [5]:
dataset = [ 
(array([0,0,1]), 0), 
(array([0,1,1]), 1), 
(array([1,0,1]), 1), 
(array([1,1,1]), 1), 
] 
print(dataset)
print(array([0,0,1]),0)

[(array([0, 0, 1]), 0), (array([0, 1, 1]), 1), (array([1, 0, 1]), 1), (array([1, 1, 1]), 1)]
[0 0 1] 0


**initializing random numbers for WEIGHTS**

In [6]:
weights = random.rand(3)
weights

array([0.92910701, 0.34122668, 0.09629822])

**initializing additional variables**

In [7]:
r = 0.4
n = 100

**Step Activation Fn**

In [12]:
activation_fn = lambda x: 0 if x < 0 else 1
for j in range(n):
    x , expected  = choice(dataset)
    res = dot(weights , x)
    err = expected - activation_fn(res)
    weights += r * err * x
for x ,_ in dataset:
    res = dot( x , weights)
    print("ResultBAFn : {} ResultAFN:{}".format(round(res,3), activation_fn(res)))

ResultBAFn : -0.304 ResultAFN:0
ResultBAFn : 0.038 ResultAFN:1
ResultBAFn : 0.625 ResultAFN:1
ResultBAFn : 0.967 ResultAFN:1


**Linear activation Fn**

In [15]:
activaitonFn = lambda x: x
for j in range(n):
    x , expected = choice(dataset)
    resu = dot(weights , x)
    err = expected - activaitonFn(resu)
    weights += r * err * x
for x , _ in dataset:
    resu = dot(x , weights)
    print("ResultBAFn : {} ResultAFN:{}".format(round(res,3), activation_fn(res)))

ResultBAFn : 0.967 ResultAFN:1
ResultBAFn : 0.967 ResultAFN:1
ResultBAFn : 0.967 ResultAFN:1
ResultBAFn : 0.967 ResultAFN:1


**Sigmoid Activatoin fn**

In [18]:
import numpy as np 
activationFn = lambda x: 1/(1+np.exp(-x)) 
for j in range(n): 
    x, expected = choice (dataset) 
    result = dot (weights, x) 
    err = expected-activationFn(result)
    weights += r * err * x 
for x, _ in dataset:  
    result = dot(x, weights) 
    print("ResultBAFn: {} ResultAFn: {}".format(round (result,3), activationFn(result))) 


ResultBAFn: -1.134 ResultAFn: 0.24350410001281214
ResultBAFn: 1.632 ResultAFn: 0.8364365100726693
ResultBAFn: 1.433 ResultAFn: 0.8072926104843123
ResultBAFn: 4.198 ResultAFn: 0.9851972075501553


**ReLu Actiavton fn**

In [20]:
activationFn = lambda x: 0 if x < 0 else x 
for j in range(n): 
    x, expected = choice(dataset) 
    result = dot(weights, x) 
    err = expected-activationFn(result)
    weights += r * err * x 
for x, _  in dataset: 
    result = dot(x, weights) 
    print("ResultBAFn: {} ResultAFn: {}".format(round (result,3), activationFn(result)))

ResultBAFn: 0.337 ResultAFn: 0.336941033466641
ResultBAFn: 1.037 ResultAFn: 1.0365251896741157
ResultBAFn: 0.836 ResultAFn: 0.8355022461623036
ResultBAFn: 1.535 ResultAFn: 1.5350864023697781
